const products = [
  /* ===================== FRUITS ===================== */
  {
    name: "Red Apple",
    image: "/assets/images/products/fruits/apple-red.jpg",
    description: "Crisp and sweet fresh red apples, handpicked for peak freshness.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 2.5,
    countInStock: 45,
    rating: 4.8,
    numReviews: 24
  },
  {
    name: "Green Apple",
    image: "/assets/images/products/fruits/apple-green.jpg",
    description: "Crisp and tart Granny Smith green apples.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 2.8,
    countInStock: 35,
    rating: 4.7,
    numReviews: 18
  },
  {
    name: "Banana",
    image: "/assets/images/products/fruits/banana.jpg",
    description: "Naturally ripened sweet bananas packed with potassium.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 1.9,
    countInStock: 60,
    rating: 4.9,
    numReviews: 42
  },
  {
    name: "Valencia Orange",
    image: "/assets/images/products/fruits/orange.jpg",
    description: "Juicy, vitamin C-rich Valencia oranges, perfect for eating or juicing.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 2.2,
    countInStock: 50,
    rating: 4.8,
    numReviews: 30
  },
  {
    name: "Mandarin Clementine",
    image: "/assets/images/products/fruits/mandarin.jpg",
    description: "Easy-to-peel sweet and fragrant seedless clementines.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 2.3,
    countInStock: 40,
    rating: 4.6,
    numReviews: 15
  },
  {
    name: "Fresh Lemon",
    image: "/assets/images/products/fruits/lemon.jpg",
    description: "Zesty and aromatic fresh local lemons.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 1.8,
    countInStock: 70,
    rating: 4.7,
    numReviews: 22
  },
  {
    name: "Pink Grapefruit",
    image: "/assets/images/products/fruits/grapefruit.jpg",
    description: "Ruby red bittersweet and refreshing grapefruit.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 2.6,
    countInStock: 25,
    rating: 4.5,
    numReviews: 12
  },
  {
    name: "Fresh Strawberry",
    image: "/assets/images/products/fruits/strawberry.jpg",
    description: "Sweet, fragrant and vibrant red garden strawberries.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 4.5,
    countInStock: 25,
    rating: 4.9,
    numReviews: 38
  },
  {
    name: "Plump Red Cherries",
    image: "/assets/images/products/fruits/cherry.jpg",
    description: "Sweet mountain-grown red cherries, firm and juicy.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 8.5,
    countInStock: 15,
    rating: 5.0,
    numReviews: 29
  },
  {
    name: "Juicy Peach",
    image: "/assets/images/products/fruits/peach.jpg",
    description: "Aromatic and soft yellow peaches, bursting with sweet juice.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.5,
    countInStock: 25,
    rating: 4.8,
    numReviews: 19
  },
  {
    name: "Fresh Nectarine",
    image: "/assets/images/products/fruits/nectarine.jpg",
    description: "Smooth-skinned sweet nectarines with honey undertones.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.8,
    countInStock: 20,
    rating: 4.7,
    numReviews: 14
  },
  {
    name: "Sweet Apricot",
    image: "/assets/images/products/fruits/apricot.jpg",
    description: "Golden aromatic apricots, tender and delicately sweet.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 4.0,
    countInStock: 18,
    rating: 4.6,
    numReviews: 16
  },
  {
    name: "White Seedless Grapes",
    image: "/assets/images/products/fruits/grape-white.jpg",
    description: "Crisp and refreshing sweet green table grapes.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.2,
    countInStock: 30,
    rating: 4.8,
    numReviews: 26
  },
  {
    name: "Black Seedless Grapes",
    image: "/assets/images/products/fruits/grape-black.jpg",
    description: "Richly flavored antioxidant dark black grapes.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.4,
    countInStock: 25,
    rating: 4.7,
    numReviews: 20
  },
  {
    name: "Sweet Watermelon",
    image: "/assets/images/products/fruits/watermelon.jpg",
    description: "Crisp, deeply hydrating and sugary sweet whole watermelon.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 1.2,
    countInStock: 80,
    rating: 4.9,
    numReviews: 55
  },
  {
    name: "Cantaloupe Melon",
    image: "/assets/images/products/fruits/melon.jpg",
    description: "Aromatic orange-flesh sweet cantaloupe melon.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 1.6,
    countInStock: 40,
    rating: 4.7,
    numReviews: 21
  },
  {
    name: "Hass Avocado",
    image: "/assets/images/products/fruits/avocado.jpg",
    description: "Creamy, buttery Hass avocados, rich in healthy omega fats.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 4.8,
    countInStock: 30,
    rating: 4.9,
    numReviews: 44
  },
  {
    name: "Ruby Pomegranate",
    image: "/assets/images/products/fruits/pomegranate.jpg",
    description: "Sweet and tart ruby-red pomegranate arils bursting with antioxidants.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.5,
    countInStock: 30,
    rating: 4.8,
    numReviews: 27
  },
  {
    name: "Fresh Baladi Fig",
    image: "/assets/images/products/fruits/fig.jpg",
    description: "Melt-in-your-mouth honey-sweet green and black figs.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 5.5,
    countInStock: 18,
    rating: 5.0,
    numReviews: 33
  },
  {
    name: "Fresh Bartlett Pear",
    image: "/assets/images/products/fruits/pear.jpg",
    description: "Sweet, aromatic and juicy green pears.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.0,
    countInStock: 25,
    rating: 4.6,
    numReviews: 17
  },
  {
    name: "Persimmon (Kaki)",
    image: "/assets/images/products/fruits/persimmon.jpg",
    description: "Sweet and rich autumn persimmons with smooth honey flavor.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 3.8,
    countInStock: 20,
    rating: 4.7,
    numReviews: 12
  },
  {
    name: "Fresh Blueberries",
    image: "/assets/images/products/fruits/blueberry.jpg",
    description: "Plump, antioxidant-rich sweet blueberries.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "pack",
    price: 3.8,
    countInStock: 20,
    rating: 4.9,
    numReviews: 31
  },
  {
    name: "Green Kiwi",
    image: "/assets/images/products/fruits/kiwi.jpg",
    description: "Tangy-sweet vitamin-rich fresh kiwi fruit.",
    brand: "Chocair Fresh",
    category: "Fruits",
    unit: "kg",
    price: 5.0,
    countInStock: 25,
    rating: 4.6,
    numReviews: 19
  },

  /* ===================== VEGETABLES ===================== */
  {
    name: "Fresh Vine Tomato",
    image: "/assets/images/products/vegetables/tomato.jpg",
    description: "Firm, flavorful and juicy red vine tomatoes for salads and cooking.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 2.2,
    countInStock: 65,
    rating: 4.8,
    numReviews: 40
  },
  {
    name: "Cherry Tomatoes",
    image: "/assets/images/products/vegetables/cherry-tomato.jpg",
    description: "Bite-sized sweet and tangy cherry tomatoes.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 3.5,
    countInStock: 30,
    rating: 4.9,
    numReviews: 28
  },
  {
    name: "Local Potatoes",
    image: "/assets/images/products/vegetables/potato.jpg",
    description: "Versatile, earthy golden potatoes perfect for roasting, baking, or mashing.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 1.5,
    countInStock: 100,
    rating: 4.8,
    numReviews: 50
  },
  {
    name: "Sweet Potato",
    image: "/assets/images/products/vegetables/sweet-potato.jpg",
    description: "Nutritious orange-fleshed sweet potatoes, naturally sweet and fiber-rich.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 2.4,
    countInStock: 45,
    rating: 4.8,
    numReviews: 23
  },
  {
    name: "Red Onion",
    image: "/assets/images/products/vegetables/onion-red.jpg",
    description: "Crisp and pungent red onions, delicious in salads and dressings.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 1.8,
    countInStock: 70,
    rating: 4.7,
    numReviews: 31
  },
  {
    name: "White Onion",
    image: "/assets/images/products/vegetables/onion-white.jpg",
    description: "Essential culinary white cooking onions with balanced flavor.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 1.6,
    countInStock: 70,
    rating: 4.6,
    numReviews: 25
  },
  {
    name: "Fresh Garlic",
    image: "/assets/images/products/vegetables/garlic.jpg",
    description: "Strong aromatic garlic bulbs with firm, flavorful cloves.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 3.8,
    countInStock: 35,
    rating: 4.8,
    numReviews: 33
  },
  {
    name: "Romaine Lettuce",
    image: "/assets/images/products/vegetables/lettuce.jpg",
    description: "Crisp and crunchy green romaine lettuce head, essential for Fattoush.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "piece",
    price: 1.0,
    countInStock: 50,
    rating: 4.8,
    numReviews: 35
  },
  {
    name: "Iceberg Lettuce",
    image: "/assets/images/products/vegetables/iceberg-lettuce.jpg",
    description: "Cool, compact and crisp iceberg lettuce head for fresh salads.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "piece",
    price: 1.2,
    countInStock: 40,
    rating: 4.6,
    numReviews: 22
  },
  {
    name: "Green Bell Pepper",
    image: "/assets/images/products/vegetables/bell-pepper-green.jpg",
    description: "Crunchy and fresh green bell peppers.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 3.0,
    countInStock: 35,
    rating: 4.7,
    numReviews: 18
  },
  {
    name: "Red Bell Pepper",
    image: "/assets/images/products/vegetables/bell-pepper-red.jpg",
    description: "Sweet, juicy and vitamin-rich red bell peppers.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 3.8,
    countInStock: 30,
    rating: 4.8,
    numReviews: 24
  },
  {
    name: "Yellow Bell Pepper",
    image: "/assets/images/products/vegetables/bell-pepper-yellow.jpg",
    description: "Mild and sweet bright yellow bell peppers.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 4.0,
    countInStock: 25,
    rating: 4.7,
    numReviews: 16
  },
  {
    name: "Hot Chili Pepper",
    image: "/assets/images/products/vegetables/chili-pepper.jpg",
    description: "Spicy fresh red and green chili peppers for seasoning.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 4.5,
    countInStock: 20,
    rating: 4.6,
    numReviews: 14
  },
  {
    name: "Dark Eggplant",
    image: "/assets/images/products/vegetables/eggplant.jpg",
    description: "Glossy, firm dark purple eggplants perfect for grilling and Mutabbal.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 2.5,
    countInStock: 40,
    rating: 4.8,
    numReviews: 27
  },
  {
    name: "Fresh Zucchini (Kousa)",
    image: "/assets/images/products/vegetables/zucchini.jpg",
    description: "Tender light-green local zucchini, ideal for stuffing or sautéing.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 2.3,
    countInStock: 45,
    rating: 4.7,
    numReviews: 29
  },
  {
    name: "Fresh Broccoli",
    image: "/assets/images/products/vegetables/broccoli.jpg",
    description: "Dense, vibrant green broccoli crowns loaded with fiber and nutrients.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "piece",
    price: 2.2,
    countInStock: 30,
    rating: 4.8,
    numReviews: 31
  },
  {
    name: "White Cauliflower",
    image: "/assets/images/products/vegetables/cauliflower.jpg",
    description: "Clean, crisp white cauliflower head for roasting or frying.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "piece",
    price: 2.0,
    countInStock: 30,
    rating: 4.7,
    numReviews: 20
  },
  {
    name: "White Cabbage",
    image: "/assets/images/products/vegetables/cabbage-white.jpg",
    description: "Crisp white cabbage head, ideal for fresh slaws and Malfouf rolls.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "piece",
    price: 1.5,
    countInStock: 30,
    rating: 4.6,
    numReviews: 18
  },
  {
    name: "Red Cabbage",
    image: "/assets/images/products/vegetables/cabbage-red.jpg",
    description: "Vibrant red cabbage, crunchy and nutrient-dense.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "piece",
    price: 1.8,
    countInStock: 25,
    rating: 4.7,
    numReviews: 15
  },
  {
    name: "Fresh Spinach Leaves",
    image: "/assets/images/products/vegetables/spinach.jpg",
    description: "Tender, iron-packed farm-fresh dark green spinach leaves.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "bunch",
    price: 1.2,
    countInStock: 40,
    rating: 4.9,
    numReviews: 36
  },
  {
    name: "Swiss Chard (Selleq)",
    image: "/assets/images/products/vegetables/swiss-chard.jpg",
    description: "Broad leafy green chard with crisp white stalks, traditional for soups.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "bunch",
    price: 1.2,
    countInStock: 40,
    rating: 4.7,
    numReviews: 19
  },
  {
    name: "Snap Green Beans (Loubieh)",
    image: "/assets/images/products/vegetables/green-beans.jpg",
    description: "Tender and crisp snap green beans for Mediterranean stews.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 3.9,
    countInStock: 30,
    rating: 4.8,
    numReviews: 24
  },
  {
    name: "White Button Mushrooms",
    image: "/assets/images/products/vegetables/mushroom.jpg",
    description: "Plump white cultivated button mushrooms, mild and earthy.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 5.5,
    countInStock: 25,
    rating: 4.9,
    numReviews: 34
  },
  {
    name: "Red Radish (Fijel)",
    image: "/assets/images/products/vegetables/radish.jpg",
    description: "Crisp and peppery red radishes with refreshing bite.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "bunch",
    price: 1.0,
    countInStock: 35,
    rating: 4.6,
    numReviews: 16
  },
  {
    name: "White Turnip (Lift)",
    image: "/assets/images/products/vegetables/turnip.jpg",
    description: "Fresh firm white turnips, great for roasting and pickling.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 1.6,
    countInStock: 30,
    rating: 4.5,
    numReviews: 13
  },
  {
    name: "Baby Okra (Bamia)",
    image: "/assets/images/products/vegetables/okra.jpg",
    description: "Tender small green okra pods, perfect for rich tomato stew.",
    brand: "Chocair Fresh",
    category: "Vegetables",
    unit: "kg",
    price: 4.8,
    countInStock: 20,
    rating: 4.8,
    numReviews: 22
  },

  /* ===================== HERBS ===================== */
  {
    name: "Fresh Parsley (Baqdounis)",
    image: "/assets/images/products/herbs/parsley.jpg",
    description: "Fragrant flat-leaf parsley bunch, the core of authentic Lebanese Tabbouleh.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 0.5,
    countInStock: 120,
    rating: 5.0,
    numReviews: 65
  },
  {
    name: "Fresh Basil (Rihan)",
    image: "/assets/images/products/herbs/basil.jpg",
    description: "Sweet, intensely aromatic fresh Mediterranean basil leaves.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 0.8,
    countInStock: 80,
    rating: 4.9,
    numReviews: 38
  },
  {
    name: "Fresh Rosemary",
    image: "/assets/images/products/herbs/rosemary.jpg",
    description: "Woodsy, piney aromatic rosemary sprigs for meat and roast vegetables.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 0.9,
    countInStock: 60,
    rating: 4.8,
    numReviews: 24
  },
  {
    name: "Fresh Oregano / Green Zaatar",
    image: "/assets/images/products/herbs/oregano.jpg",
    description: "Wild Lebanese mountain oregano and fresh green zaatar leaves.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 0.9,
    countInStock: 60,
    rating: 4.9,
    numReviews: 31
  },
  {
    name: "Fresh Green Onion (Scallions)",
    image: "/assets/images/products/herbs/green-onion.jpg",
    description: "Crisp spring onions with mild green stalks and pungent white bulbs.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 0.6,
    countInStock: 90,
    rating: 4.8,
    numReviews: 42
  },
  {
    name: "Fresh Leek",
    image: "/assets/images/products/herbs/leek.jpg",
    description: "Mild, sweet onion-flavored leek stalks, ideal for gourmet soups.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 1.2,
    countInStock: 40,
    rating: 4.7,
    numReviews: 18
  },
  {
    name: "Fresh Fennel Bulb",
    image: "/assets/images/products/herbs/fennel.jpg",
    description: "Crunchy fennel bulb with delicate anise flavor and feathery fronds.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "piece",
    price: 1.5,
    countInStock: 30,
    rating: 4.6,
    numReviews: 15
  },
  {
    name: "Fresh Chives",
    image: "/assets/images/products/herbs/chives.jpg",
    description: "Delicate green chives with mild garlic-onion aroma.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 1.0,
    countInStock: 40,
    rating: 4.7,
    numReviews: 16
  },
  {
    name: "Fresh Bay Leaves",
    image: "/assets/images/products/herbs/bay-leaves.jpg",
    description: "Aromatic laurel bay leaves for rich broths, sauces, and stews.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 0.9,
    countInStock: 50,
    rating: 4.8,
    numReviews: 20
  },
  {
    name: "Fresh Tarragon (Tarkhoun)",
    image: "/assets/images/products/herbs/tarragon.jpg",
    description: "Aromatic sweet herbal tarragon with subtle licorice notes.",
    brand: "Chocair Fresh",
    category: "Herbs",
    unit: "bunch",
    price: 1.2,
    countInStock: 35,
    rating: 4.6,
    numReviews: 12
  },

  /* ===================== RAW NUTS ===================== */
  {
    name: "Raw Whole Almonds",
    image: "/assets/images/products/nuts/almond-raw.jpg",
    description: "100% natural unpasteurized whole raw almonds, high in vitamin E.",
    brand: "Chocair Fresh",
    category: "Raw Nuts",
    unit: "kg",
    price: 12.0,
    countInStock: 35,
    rating: 4.9,
    numReviews: 32
  },
  {
    name: "Raw Walnut Halves",
    image: "/assets/images/products/nuts/walnut.jpg",
    description: "Shelled premium light walnut halves rich in heart-healthy Omega-3.",
    brand: "Chocair Fresh",
    category: "Raw Nuts",
    unit: "kg",
    price: 11.0,
    countInStock: 30,
    rating: 4.9,
    numReviews: 28
  },
  {
    name: "Raw Pine Nuts (Snobar Baladi)",
    image: "/assets/images/products/nuts/pine-nuts.jpg",
    description: "Premium fragrant raw pine nuts, a staple for Mediterranean gourmet dishes.",
    brand: "Chocair Fresh",
    category: "Raw Nuts",
    unit: "kg",
    price: 28.0,
    countInStock: 15,
    rating: 5.0,
    numReviews: 25
  },
  {
    name: "Raw Macadamia Nuts",
    image: "/assets/images/products/nuts/macadamia.jpg",
    description: "Luxuriously rich, buttery whole raw macadamia nuts.",
    brand: "Chocair Fresh",
    category: "Raw Nuts",
    unit: "kg",
    price: 30.0,
    countInStock: 12,
    rating: 4.9,
    numReviews: 16
  },
  {
    name: "Raw Pumpkin Seeds (Pepitas)",
    image: "/assets/images/products/nuts/pumpkin-seeds.jpg",
    description: "Shelled raw green pumpkin seeds, loaded with zinc and magnesium.",
    brand: "Chocair Fresh",
    category: "Raw Nuts",
    unit: "kg",
    price: 9.5,
    countInStock: 25,
    rating: 4.7,
    numReviews: 18
  },
  {
    name: "Raw Sunflower Seeds",
    image: "/assets/images/products/nuts/sunflower-seeds.jpg",
    description: "Clean shelled raw sunflower kernels, rich in healthy fats and nutrients.",
    brand: "Chocair Fresh",
    category: "Raw Nuts",
    unit: "kg",
    price: 5.0,
    countInStock: 30,
    rating: 4.6,
    numReviews: 15
  },

  /* ===================== COOKED NUTS ===================== */
  {
    name: "Oven Roasted Cashews",
    image: "/assets/images/products/nuts/cashew-roasted.jpg",
    description: "Crunchy golden oven-roasted salted whole cashew nuts.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 15.0,
    countInStock: 25,
    rating: 4.9,
    numReviews: 35
  },
  {
    name: "Roasted Pistachios In-Shell",
    image: "/assets/images/products/nuts/pistachio-unshelled.jpg",
    description: "Oven-roasted salted Turkish-style pistachios in shell.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 16.0,
    countInStock: 25,
    rating: 4.9,
    numReviews: 40
  },
  {
    name: "Shelled Roasted Pistachios",
    image: "/assets/images/products/nuts/pistachio-shelled.jpg",
    description: "Peeled and lightly roasted pistachio kernels, ready for snacking.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 18.0,
    countInStock: 20,
    rating: 5.0,
    numReviews: 29
  },
  {
    name: "Roasted Hazelnuts (Bandouk)",
    image: "/assets/images/products/nuts/hazelnut.jpg",
    description: "Blanched and toasted crunchy hazelnuts with aromatic roasted aroma.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 13.0,
    countInStock: 20,
    rating: 4.8,
    numReviews: 21
  },
  {
    name: "Salted Roasted Peanuts",
    image: "/assets/images/products/nuts/peanut.jpg",
    description: "Classic crunchy oven-roasted salted peanuts.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 6.0,
    countInStock: 40,
    rating: 4.7,
    numReviews: 30
  },
  {
    name: "Deluxe Roasted Mixed Nuts",
    image: "/assets/images/products/nuts/mixed-nuts.jpg",
    description: "Special blend of roasted cashews, almonds, pistachios, and hazelnuts.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 16.0,
    countInStock: 30,
    rating: 5.0,
    numReviews: 48
  },
  {
    name: "Crispy Roasted Chickpeas (Qadameh)",
    image: "/assets/images/products/nuts/chickpeas-roasted.jpg",
    description: "Traditional Middle Eastern crispy roasted yellow chickpeas.",
    brand: "Chocair Fresh",
    category: "Cooked Nuts",
    unit: "kg",
    price: 6.5,
    countInStock: 35,
    rating: 4.7,
    numReviews: 22
  },

  /* ===================== DATES ===================== */
  {
    name: "Jumbo Medjool Dates",
    image: "/assets/images/products/dates/medjool-dates.jpg",
    description: "The King of Dates: exceptionally large, plump, soft with rich caramel sweetness.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 10.0,
    countInStock: 40,
    rating: 5.0,
    numReviews: 52
  },
  {
    name: "Ajwa Al-Madinah Dates",
    image: "/assets/images/products/dates/ajwa-dates.jpg",
    description: "Authentic Ajwa dates from Madinah, known for high spiritual and nutritional value.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 14.0,
    countInStock: 25,
    rating: 5.0,
    numReviews: 46
  },
  {
    name: "Golden Sukkari Dates",
    image: "/assets/images/products/dates/sukkari-dates.jpg",
    description: "Golden honey-toned, melt-in-your-mouth sweet Sukkari dates.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 11.0,
    countInStock: 30,
    rating: 4.9,
    numReviews: 34
  },
  {
    name: "Deglet Noor Dates",
    image: "/assets/images/products/dates/deglet-noor.jpg",
    description: "Translucent honey-colored dates with firm chewy bite.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 8.0,
    countInStock: 35,
    rating: 4.8,
    numReviews: 26
  },
  {
    name: "Khudri Dates",
    image: "/assets/images/products/dates/khudri-dates.jpg",
    description: "Uniform cylindrical dark dates, moderately sweet and chewy.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 9.0,
    countInStock: 25,
    rating: 4.7,
    numReviews: 20
  },
  {
    name: "Fresh Barhi Dates",
    image: "/assets/images/products/dates/barhi-dates.jpg",
    description: "Crisp and golden fresh Barhi dates with natural butterscotch taste.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 12.0,
    countInStock: 18,
    rating: 4.9,
    numReviews: 22
  },
  {
    name: "Mabroom Dates",
    image: "/assets/images/products/dates/mabroom-dates.jpg",
    description: "Long slender dates with pleasant chew and mild sweet flavor.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 13.0,
    countInStock: 20,
    rating: 4.8,
    numReviews: 24
  },
  {
    name: "Safawi Dates",
    image: "/assets/images/products/dates/safawi-dates.jpg",
    description: "Deep black soft dates packed with essential minerals and energy.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "kg",
    price: 10.5,
    countInStock: 25,
    rating: 4.8,
    numReviews: 21
  },
  {
    name: "Stuffed Gourmet Dates Gift Box",
    image: "/assets/images/products/dates/stuffed-dates.jpg",
    description: "Premium Medjool dates stuffed with almonds, walnuts, pistachios and orange peel.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "box",
    price: 7.5,
    countInStock: 25,
    rating: 5.0,
    numReviews: 39
  },
  {
    name: "Pure Natural Date Paste",
    image: "/assets/images/products/dates/date-paste.jpg",
    description: "100% natural smooth pitted date paste, perfect for baking Maamoul.",
    brand: "Chocair Fresh",
    category: "Dates",
    unit: "box",
    price: 5.0,
    countInStock: 30,
    rating: 4.8,
    numReviews: 18
  }
];

export default products;
